- title: Catering
  body: Lorem ipsum dolor sit amet, consectetur  elit, sed do eiusmod tempor incididunt ut
  icon: fa-cutlery

- title: Conference Services
  body: Lorem ipsum dolor sit amet, consectetur  elit, sed do eiusmod tempor incididunt ut
  icon: fa-bullhorn

- title: Room Setup
  body: Lorem ipsum dolor sit amet, consectetur  elit, sed do eiusmod tempor incididunt ut
  icon: fa-plug

- title: Audio/Visuals
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  icon: fa-music

- title: Printing
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  icon: fa-print

- title: WiFi
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  icon: fa-wifi

- title: Floor Planning
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  icon: fa-map-signs

- title: Parking
  body: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  icon: fa-car
